### ISSUE TITLE
Not working with Python 3.7.7

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-cli#27]
I have python3.7.7 installed and get this error:
```
ImportError: cannot import name 'cached_property' from 'functools' (/Users/tobias/.virtualenvs/safe-cli/lib/python3.7/functools.py)
```

Seems like cached_property isn't available in python < 3.8: https://docs.python.org/3.7/library/functools.html
